### ISSUE TITLE
 The system cannot find the path specified

### ISSUE THREAD

**Issue by nitek29** [maaaaz/CrackMapExecWin#4]
Hey,
Have you ever had this problem? I try to fix it for a few days but nothing works.
```powershell
PS C:\Users\IEUser\Documents\CrackMapExec> .\dist\crackmapexec.exe
Traceback (most recent call last):
  File "cme\crackmapexec.py", line 5, in <module>
    from cme.logger import setup_logger, setup_debug_logger, CMEAdapter
  File "c:\users\ieuser\appdata\local\temp\pip-install-q2t2ut\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
  File "cme\__init__.py", line 10, in <module>
    for module in os.listdir(thirdparty_modules):
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Users\\IEUser\\AppData\\Local\\Temp\\_MEI47~1\\cme\\thirdparty/*.*'
[6520] Failed to execute script crackmapexec
```

**Comment by maaaaz** [comment]
Hello @nitek29,
From what I see I think that you're trying to compile the latest CME major version (thing that I didn't do since a long time).

The error seems to come from the fact that a windows-style path `C:\\Users\\IEUser\\AppData\\Local\\Temp\\_MEI47~1\\cme\thirdparty` is mixed with a unix-style path `/*.*`

Try to normalize path in the CME Python program beforehand.

Cheers.

**Comment by maaaaz** [comment]
https://github.com/maaaaz/CrackMapExecWin/issues/6
